import { StrictMode, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './style.css'

type Page={title:string;intro:string;body:JSX.Element}
const nav=[['quickstart','快速开始'],['privacy','隐私与安全']]
function PageBody({id}:{id:string}){const pages:Record<string,Page>={
quickstart:{title:'快速开始',intro:'从第一次扫描开始，了解项目里有哪些智能体组件、它们如何连接，以及哪些风险需要优先处理。',body:<><h2 id="steps">三步完成第一次扫描</h2><div className="steps"><Step n="01" t="选择输入" d="选择本地目录、ZIP，或公开 Git HTTPS 仓库。"/><Step n="02" t="开始扫描" d="AgentScan 在本地读取静态文件并构建分析图。"/><Step n="03" t="审查发现" d="沿着风险路径查看组件、来源位置和修复建议。"/></div><h2 id="result">扫描完成后看什么</h2><p>先从 Finding 开始，查看风险等级、原因和最小来源证据；再打开 AgentBOM 了解组件；最后沿图中的路径确认风险从智能体、模型到工具的连接。</p></>},
install:{title:'安装 AgentScan',intro:'选择你的操作系统，下载应用并启动第一次本地扫描。',body:<><h2 id="platform">平台支持</h2><div className="table"><b>macOS</b><span>arm64、x64</span><b>Linux</b><span>x64</span><b>Windows</b><span>当前未发布</span></div><h2 id="download">下载安装包</h2><p>从 <a href="https://github.com/aicensus-labs/AgentScan/releases" target="_blank" rel="noreferrer">GitHub Releases ↗</a> 下载对应平台的安装包。安装用户不需要预先安装 Python、Node.js、Git 或项目依赖。</p><h2 id="check">启动前检查</h2><p>首次运行后，选择一个明确授权的项目目录或归档。AgentScan 会在受控的临时目录中完成材料准备和分析。</p></>},
scan:{title:'扫描项目',intro:'AgentScan 支持三种输入方式，每种输入都会先经过边界检查和本地化处理。',body:<><h2 id="local">本地目录</h2><p>选择一个项目目录。扫描只读取授权目录中的静态文件，不修改源代码，也不会运行项目。</p><h2 id="zip">ZIP 压缩包</h2><p>选择一个 ZIP 文件导入。危险路径、符号链接、特殊文件和超过资源限制的归档会被拒绝。</p><h2 id="git">公开 Git 仓库</h2><p>输入无凭据的公开 HTTPS Git 地址。AgentScan 使用受限的浅克隆，不获取子模块、Git LFS、hooks 或凭据。</p></>},
report:{title:'理解报告',intro:'报告把风险发现、组件清单和来源证据放在同一条可追溯路径上。',body:<><h2 id="order">推荐阅读顺序</h2><ol><li>先看 Finding 的严重性、置信度和原因。</li><li>打开来源证据，确认结论对应的文件和位置。</li><li>沿风险路径查看智能体、模型和工具之间的关系。</li><li>结合 remediation 判断下一步修改方向。</li></ol><h2 id="areas">三个核心区域</h2><p><b>Finding</b> 表示风险结论；<b>AgentBOM</b> 展示确认过的组件；图展示语义连接和风险经过的路径。</p></>},
capabilities:{title:'扫描能力',intro:'了解当前版本支持的输入、输出和运行边界。',body:<><h2 id="support">当前支持</h2><p>支持本地目录、ZIP 和公开 Git HTTPS 输入；提供 AgentBOM、Finding、风险图、来源位置、分析警告和输入 provenance。</p><h2 id="scope">分析范围</h2><p>AgentFlow 负责框架语义和风险分析，AgentScan 负责安全获取、生命周期管理、结果校验、脱敏和展示。</p><h2 id="limits">当前限制</h2><p>报告持久化与导出、Windows、Linux arm64 以及运行时动态监控暂不属于当前版本能力。</p></>},
privacy:{title:'隐私与安全',intro:'AgentScan 面向本地静态分析设计，扫描材料不会被当作可执行程序处理。',body:<><h2 id="execute">不会执行什么</h2><p>不会执行项目代码、导入模块、安装依赖、运行 package scripts、加载插件、启动智能体或工具，也不会连接项目配置中的端点。</p><h2 id="data">数据如何处理</h2><p>输入材料在 AgentScan 管理的临时目录中处理。结果跨进程展示前会经过字段投影、路径最小化和秘密形状值脱敏，临时结果在扫描结束后清理。</p><h2 id="warnings">分析警告</h2><p>读取、解码、解析或资源限制错误会作为警告保留，不会被转换成“没有风险”的结论。</p></>}}
const page=id==='quickstart'?{title:'快速开始',intro:pages.quickstart.intro,body:<>{pages.quickstart.body}{pages.install.body}{pages.scan.body}{pages.report.body}{pages.capabilities.body}</>}:pages.privacy;const toc=id==='quickstart'?[['steps','三步完成第一次扫描'],['platform','平台支持'],['local','选择项目'],['order','理解报告'],['support','扫描能力']]:id==='install'?[['platform','平台支持'],['download','下载安装包'],['check','启动前检查']]:id==='scan'?[['local','本地目录'],['zip','ZIP 压缩包'],['git','公开 Git 仓库']]:id==='report'?[['order','推荐阅读顺序'],['areas','三个核心区域']]:id==='capabilities'?[['support','当前支持'],['scope','分析范围'],['limits','当前限制']]:id==='privacy'?[['execute','不会执行什么'],['data','数据如何处理'],['warnings','分析警告']]:[['steps','三步完成第一次扫描'],['result','扫描完成后看什么']];return <article><div className="eyebrow">AgentScan 文档</div><h1>{page.title}</h1><p className="lead">{page.intro}</p><hr/>{page.body}{id==='quickstart'&&<><h2>更多资源</h2><div className="links"><a href="https://github.com/aicensus-labs/AgentScan/releases" target="_blank" rel="noreferrer"><b>下载</b><small>获取 AgentScan 安装包 ↗</small></a><a href="https://github.com/aicensus-labs/AgentScan" target="_blank" rel="noreferrer"><b>源代码</b><small>查看项目源码 ↗</small></a><a href="https://github.com/aicensus-labs/AgentScan/issues" target="_blank" rel="noreferrer"><b>咨询</b><small>在 GitHub Issues 提问 ↗</small></a></div></>}</article>}
function Step({n,t,d}:{n:string;t:string;d:string}){return <div className="step"><span>{n}</span><h3>{t}</h3><p>{d}</p></div>}
function App(){const [id,setId]=useState(location.hash.slice(1)||'quickstart');useEffect(()=>{const f=()=>setId(location.hash.slice(1)||'quickstart');addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f)},[]);return <div className="shell"><aside><div className="brand"><span className="mark">A</span> AgentScan</div><div className="label">指南</div>{nav.slice(0,1).map(([key,label])=><a className={id===key?'active sub':''} href={'#'+key} key={key}>{label}</a>)}<div className="label">参考</div>{nav.slice(1).map(([key,label])=><a className={id===key?'active':''} href={'#'+key} key={key}>{label}</a>)}</aside><main><header><div className="search"><span>⌕</span><input aria-label="搜索文档" placeholder="搜索文档"/></div></header><PageBody id={id}/></main></div>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>)
